//
import Head from "next/head";
import Surahs from "../../components/surah";
import Styles from "../../styles/detail.module.scss";


export async function getServerSideProps(context) {
  const { params } = context;
  const response = await fetch(
    `https://api.alquran.cloud/v1/surah/${params.number}/uz.sodik`
  );
  const data = await response.json();

  const responseAudio = await fetch(
    `https://api.alquran.cloud/v1/surah/${params.number}/ar.alafasy`
  );
  const dataAudio = await responseAudio.json();

  const responseArabic = await fetch(
    `http://api.alquran.cloud/v1/surah/${params.number}`
  );
  const dataArabic = await responseArabic.json();
  return {
    props: {
      data: data.data,
      dataAudio: dataAudio.data,
      dataArabic: dataArabic.data,
    },
  };
}

import image from "../../public/images/bg2.png"
import Image from "next/image";

export default function Surah({ data, dataAudio, dataArabic }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
       
      </Head>
      <h1>home</h1>
      <h2 className={Styles.nameSurah}>{data.englishName + " --- " + data.name}</h2>
      <img src="./images/bg2.png" alt="" />

      <div>
        <ul className={Styles.wrapItems}>
          {data.ayahs.map((ayah, index) => (
            <li className={Styles.itemDetail}>
              {console.log(ayah)}
              <p className={Styles.circle}>{index + 1}</p>
              <Surahs
                key={ayah.number}
                ayahIndex={ayah.number}
                text={ayah.text}
                audio={dataAudio.ayahs[index].audio}
                arabic={dataArabic.ayahs[index].text}
              ></Surahs>
              <Image src={image} alt="asdas" />
            </li>
          ))}
        </ul>
      </div>

      {console.log(data)}
    </div>
  );
}
