import Head from "next/head";
import Surahs from "../../components/surah";
import Styles from "../../styles/detail.module.scss";
import Link from "next/link";
import image from "../../public/images/bg2.png";
import Image from "next/image";
import { AppWrapper } from "../../Context/AppContext";

export default function Surah({ data, dataAudio, dataArabic }) {
  return (
    <div>
      <Head>
        <title>Qur'oni Karim || Detail</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="headDetail">
        <Link href={"/surahs"}>
          <i className="fa-solid fa-angles-left"></i>
        </Link>
        <Link href={"/"}>
          <i className="fa-solid fa-house"></i>
        </Link>
      </div>

      <h2 className={Styles.nameSurah}>
        {data.englishName + " --- " + data.name}
      </h2>

      <div>
        <AppWrapper>
          <ul className={Styles.wrapItems}>
            {data.ayahs.map((ayah, index) => (
              <li className={Styles.itemDetail} key={index}>
                <p className={Styles.circle}>{index + 1}</p>
                <Surahs
                  key={ayah.number}
                  ayahIndex={ayah.number}
                  text={ayah.text}
                  audio={dataAudio.ayahs[index].audio}
                  arabic={dataArabic.ayahs[index].text}
                ></Surahs>
                <Image src={image} alt="asdas" />
              </li>
            ))}
          </ul>
        </AppWrapper>
      </div>

      {console.log(data)}
    </div>
  );
}

export async function getServerSideProps(context) {
  const { params } = context;
  const response = await fetch(
    `https://api.alquran.cloud/v1/surah/${params.number}/uz.sodik`
  );
  const data = await response.json();

  const responseAudio = await fetch(
    `https://api.alquran.cloud/v1/surah/${params.number}/ar.alafasy`
  );
  const dataAudio = await responseAudio.json();

  const responseArabic = await fetch(
    `http://api.alquran.cloud/v1/surah/${params.number}`
  );
  const dataArabic = await responseArabic.json();
  return {
    props: {
      data: data.data,
      dataAudio: dataAudio.data,
      dataArabic: dataArabic.data,
    },
  };
}
