import Head from "next/head";
import Link from "next/link";
export const getStaticProps = async () => {
  const response = await fetch("http://api.alquran.cloud/v1/surah");
  const data = await response.json();
  return {
    props: {
      data: data.data,
    },
  };
};
export default function Surahs({ data }) {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>home</h1>
      {data.map((sura, index) => {
        console.log(sura);
        return (
          <>
            <Link href={`/surahs/${sura.number}`} key={index}>
              {sura.englishName}
            </Link>
            <br />
          </>
        );
      })}
    </div>
  );
}
