import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href='/surahs'>suralar</Link>
    </div>
  );
}
